[package]
name = "tiny-soft-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
winit = { version = "0.29" }
tobj = "4"
sdl2 = { version = "0.36", features = ["bundled", "static-link"] }
